
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wm02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 13766


Logging:
  level:
    com.wms: debug